version: "3"

name: cultureup_backend

services:
  backend-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
  db:
    image: postgres:14
    ports:
      - 3849:5432
    volumes:
      - /var/lib/cultureup_db:/var/lib/postgres
    environment:
      POSTGRES_USER: cultureup
      POSTGRES_PASSWORD: .#cv17vr3vp#.
      POSTGRES_DB: cultureup
